<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)xunit.runner.json"
          Link="xunit.runner.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
