// <auto-generated: scripts/codegen/gen-build-hash.py —— DO NOT EDIT。源：LiteSim.Core/Scripts + LiteSim.Core/Systems
// + LiteNet/Proto + LiteNet/Protocol 的源码内容 + 表数据（GameData/Config）；改了 Sim/协议/表后重跑生成器。>
namespace LiteNet
{
    /// <summary>
    /// 联机版本 hash（M10 前置）：覆盖判定逻辑（Sim）与协议（Proto/Protocol）的源码内容，
    /// **两端（客户端/服务器）必须一致**——不一致 = 逻辑或协议版本不同 = 必然分叉。
    /// 用途：`JoinRequest.build_hash` 握手校验 + 启动期断言（不等 → 拒绝进房，§40/§380）；
    /// 生成与校验规则单源 = `scripts/codegen/gen-build-hash.py`（含行尾归一化，保证跨机器可复现）：
    /// 出包前由 `scripts/build/build-player.ps1` 跑 `--check` 复算拦截"改了源忘了重跑"（开发期不校验）。
    /// </summary>
    public static class BuildHash
    {
        /// <summary>当前构建的版本 hash（16 位小写 hex）。</summary>
        public const string Value = "40837e10f1e680bd";
    }
}
