// <auto-generated: scripts/gen-build-hash.py —— DO NOT EDIT。
// 源集清单**单源**：与 `scripts/gen-build-hash.py` 的 TARGETS / DATA_TARGETS / DATA_EXTS /
// DATA_EXCLUDE_NAMES / SKIP_DIRS 逐字对应，由同一脚本一并生成。
// `Tests/LiteNet.Tests/BuildHashTests` 读本文件复算——**跨语言不再各写一份**（见
// 《客户端与服务端共享代码范围专项设计》§8.1 G1：此前两处清单已漂移，守卫半失效且不报错）。>
namespace LiteNet
{
    /// <summary>BuildHash 源集清单（生成物，勿手改）。</summary>
    public static class BuildHashSourceSet
    {
        /// <summary>源码目标（相对仓库根，仅收集 *.cs）。</summary>
        public static readonly string[] Targets =
        {
            "Assets/LiteSim/Core/Scripts",
            "Assets/LiteSim/Core/Systems",
            "Assets/LiteNet/Proto",
            "Assets/LiteNet/Protocol",
            "Assets/LiteNet/Transport/Security",
        };

        /// <summary>表数据目标（相对仓库根，按 <see cref="DataExtensions"/> 白名单收集）。</summary>
        public static readonly string[] DataTargets =
        {
            "Assets/GameData/Config",
        };

        /// <summary>表数据扩展名白名单。</summary>
        public static readonly string[] DataExtensions =
        {
            ".bytes",
        };

        /// <summary>非玩法表排除（参与判定/协议以外的表不进 hash）。</summary>
        public static readonly string[] DataExcludeNames =
        {
            "tbuiform.bytes",
        };

        /// <summary>收集时跳过的目录名。</summary>
        public static readonly string[] SkipDirs =
        {
            ".dotnet",
            "Editor",
            "__pycache__",
            "bin",
            "obj",
        };

        /// <summary>生成器自身输出，收集时排除（否则自指不稳/不收敛）。</summary>
        public static readonly string[] SelfNames =
        {
            "BuildHash.g.cs",
            "BuildHashSourceSet.g.cs",
        };
    }
}
