// <auto-generated: LiteSim/根位移/烘焙 RootMotionData.g.cs —— DO NOT EDIT。
// 源：RootMotionBakeConfig（人形 RootT 曲线 60Hz 采样→毫米量化）；同配置重复烘焙逐字节一致。
// 改了片段/配置后重烘＋重跑 scripts/gen-build-hash.py（本文件在 BuildHash 源集内）。
namespace LiteSim
{
    public static partial class RootMotionCatalog
    {
        /// <summary>烘焙时点的产物摘要（RootMotionDigest 复算守卫用；对局准入两端校验）。</summary>
        public const string BakedContentDigest = "52e34840e2d207e46fc1245eb5e6d3946a1b45c5f0905b5cd61472f2f57bae98";

        public static readonly RootMotionEntry[] Entries = new RootMotionEntry[]
        {
            new RootMotionEntry { ActionId = 101, MotionVersion = 1, SampleCount = 67, DirectionPolicy = (RootMotionDirectionPolicy)0, MovementPolicy = (RootMotionMovementPolicy)0, CancelPolicy = (RootMotionCancelPolicy)0, YPeakMm = 4, DeltaLocalXzMm = new short[] { 1, 32, 0, 31, 0, 31, 0, 29, 1, 26, 1, 24, 0, 23, 0, 23, 1, 24, 1, 24, 1, 24, 1, 24, 1, 24, 1, 25, 1, 25, 1, 24, 1, 22, 0, 22, 0, 21, 0, 20, 0, 20, 0, 20, 0, 21, 0, 21, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 23, 1, 23, 0, 24, 0, 24, 0, 25, 0, 24, 0, 23, 0, 22, 0, 22, 0, 22, 0, 23, 0, 24, 0, 25, -1, 27, -1, 27, -1, 27, -1, 27, -1, 27, -1, 27, -1, 27, 0, 27, 0, 27, 0, 26, 0, 26, 0, 26, 0, 25, -1, 24, -1, 23, -1, 22, -1, 21, -1, 20, -1, 20, -1, 19, -1, 19, -1, 18, 0, 18 }, DeltaYawCentiDeg = new short[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
            new RootMotionEntry { ActionId = 102, MotionVersion = 1, SampleCount = 39, DirectionPolicy = (RootMotionDirectionPolicy)0, MovementPolicy = (RootMotionMovementPolicy)0, CancelPolicy = (RootMotionCancelPolicy)0, YPeakMm = 15, DeltaLocalXzMm = new short[] { -3, 81, -3, 81, -2, 81, -2, 82, -1, 83, 0, 84, 0, 85, 1, 87, 1, 88, 1, 93, 1, 101, 1, 104, 0, 104, 0, 99, 1, 95, 2, 94, 2, 92, 3, 91, 3, 90, 3, 88, 2, 87, 2, 85, 2, 84, 2, 82, 2, 80, 1, 78, 0, 77, -1, 75, -2, 74, -2, 74, -2, 74, -2, 73, -1, 72, -1, 71, 0, 69, 0, 67, 0, 60, -1, 74, -3, 115 }, DeltaYawCentiDeg = new short[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
            new RootMotionEntry { ActionId = 201, MotionVersion = 1, SampleCount = 81, DirectionPolicy = (RootMotionDirectionPolicy)0, MovementPolicy = (RootMotionMovementPolicy)0, CancelPolicy = (RootMotionCancelPolicy)0, YPeakMm = 42, DeltaLocalXzMm = new short[] { -67, 27, -65, 14, -62, -25, -58, -33, -52, -12, -49, -7, -51, -9, -45, -6, -29, 2, -21, 5, -19, 5, -13, 4, -6, 0, -2, -1, 1, -1, 1, -1, 0, -1, 0, -1, -1, -1, -1, 0, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 2, 0, 3, 0, 3, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 3, 0, 3, 1, 3, 1, 3, 1, 3, 1, 4, 1, 6, 1, 7, 1, 9, 1, 12, 1, 14, 1, 15, 2, 16, 2, 17, 3, 17, 3, 17, 3, 16, 4, 17, 4, 17, 4, 17, 4, 17, 3, 17, 3, 17, 3, 17, 2, 17, 2, 17, 2, 16, 1, 17, 2, 18, 2, 19, 2, 18, 1, 16, 1, 14, 0, 12, -1, 9, -2, 7, -2, 6, -2, 6, -2, 5, -2, 4, -2, 4, -2, 3, -2, 3, -2, 4, -2, 4, -3 }, DeltaYawCentiDeg = new short[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
        };
    }
}
