# ─────────────────────────────────────────────────────────────────────────────
# Environment restore check (C0-1, 2026-09-21)
#
# Per: Client Framework Master Design 14.1 / C0 - restore scripts must fail
#      clearly on missing pieces; never continue with a broken environment.
# Rules: missing BLOCKING item -> exit 1 and list every missing piece;
#        WARN items do not block.
# NOTE: keep this file ASCII-only. Windows PowerShell 5.1 parses non-BOM
#       UTF-8 files as GBK on zh-CN systems and breaks on CJK comments.
# Usage: powershell -NoProfile -File scripts/restore-check.ps1
# ─────────────────────────────────────────────────────────────────────────────
[CmdletBinding()]
param(
    [string]$ProjectPath = ''
)

if ([string]::IsNullOrWhiteSpace($ProjectPath)) {
    $here = $PSScriptRoot
    if ([string]::IsNullOrWhiteSpace($here)) { $here = Split-Path -Parent $MyInvocation.MyCommand.Path }
    $ProjectPath = (Resolve-Path (Join-Path $here '..')).Path
}

$script:blocking = New-Object System.Collections.Generic.List[string]
$script:warnings = New-Object System.Collections.Generic.List[string]
$script:ok = New-Object System.Collections.Generic.List[string]

function Ok($t)   { $script:ok.Add($t) }
function Miss($t) { $script:blocking.Add($t) }
function Warn($t) { $script:warnings.Add($t) }

Write-Host "Restore check | project: $ProjectPath" -ForegroundColor White

# -- 1. Unity project settings & version --------------------------------------
$pv = Join-Path $ProjectPath 'ProjectSettings\ProjectVersion.txt'
if (Test-Path $pv) {
    $ver = ((Get-Content $pv | Select-String 'm_EditorVersion:').ToString()) -replace 'm_EditorVersion:\s*',''
    $expected = '2022.3.55f1c1'
    if ($ver -eq $expected) { Ok "Unity $ver (matches toolchain.json)" }
    else { Miss "Unity version mismatch: got $ver, expected $expected (scripts/toolchain.json)" }
    if (-not (Test-Path (Join-Path $ProjectPath 'ProjectSettings\ProjectSettings.asset'))) {
        Miss 'ProjectSettings incomplete (not in repo; obtain from controlled source - see Docs/clone-restore guide)'
    } else { Ok 'ProjectSettings complete' }
}
else { Miss 'ProjectVersion.txt missing: ProjectSettings/ is not in the repo and must be provided (see Docs guide)' }

# -- 2. Dependency declarations: manifest / lock / vendored packages ----------
$manifest = Join-Path $ProjectPath 'Packages\manifest.json'
$lock = Join-Path $ProjectPath 'Packages\packages-lock.json'
if (-not (Test-Path $manifest)) { Miss 'Packages/manifest.json missing (must ship with repo)' }
else {
    try {
        $m = Get-Content $manifest -Raw | ConvertFrom-Json
        $bad = @()
        foreach ($p in $m.dependencies.PSObject.Properties) {
            if ($p.Value -match '^file:[A-Za-z]:' -or $p.Value -match '^file:/') { $bad += "$($p.Name)=$($p.Value)" }
            if ($p.Value -match '\.git$' -or ($p.Value -match '\.git' -and $p.Value -notmatch '\.git#[0-9a-f]{40}')) {
                $bad += "$($p.Name)=floating git dep (pin commit)"
            }
        }
        if ($bad.Count -gt 0) { Miss "manifest has personal absolute paths or floating deps: $($bad -join '; ')" }
        else { $depCount = @($m.dependencies.PSObject.Properties).Count; Ok "manifest.json reproducible ($depCount deps, zero personal paths)" }
    }
    catch { Miss "manifest.json parse failed: $($_.Exception.Message)" }
}
if (-not (Test-Path $lock)) { Warn 'packages-lock.json missing (generated by Unity; commit before push)' }
else { Ok 'packages-lock.json present' }

foreach ($pkg in @('com.tuyoogame.yooasset', 'com.code-philosophy.luban')) {
    $pkgJson = Join-Path $ProjectPath "Packages\$pkg\package.json"
    if (Test-Path $pkgJson) { Ok "vendored package present: $pkg" }
    else { Miss "vendored package missing: Packages/$pkg (must ship with repo)" }
}

# -- 3. Toolchain --------------------------------------------------------------
$dotnet = Get-Command 'dotnet' -ErrorAction SilentlyContinue
if ($dotnet) {
    $v = (& dotnet --version) 2>$null
    if ($v -match '^8\.') { Ok ".NET SDK $v" }
    else { Warn ".NET SDK $v (L1/L3 target net8.0; prefer 8.x)" }
}
else { Miss 'dotnet SDK missing (required for L1/L3 tests and RoomServer; install .NET 8 SDK)' }

$py = Get-Command 'python' -ErrorAction SilentlyContinue
if ($py) {
    $pyv = (& python --version) 2>$null
    if ($pyv -match '3\.(1[0-9]|[2-9][0-9])') {
        $openpyxl = (& python -c 'import openpyxl; print(openpyxl.__version__)') 2>$null
        if ($LASTEXITCODE -eq 0 -and $openpyxl) { Ok "Python $pyv + openpyxl $openpyxl (Luban chain)" }
        else { Miss 'python missing openpyxl (pip install openpyxl - required by Luban/gen_lua_keys.py step 3)' }
    }
    else { Warn "Python $pyv (gen_lua_keys.py needs >= 3.10)" }
}
else { Miss 'python missing (Luban gen.bat step 3 requires Python 3.10+)' }

$git = Get-Command 'git' -ErrorAction SilentlyContinue
if ($git) { Ok 'git present' } else { Miss 'git missing' }

# -- 4. Paid / restricted plugins (install validators, not redistributable) --
if (Test-Path (Join-Path $ProjectPath 'Assets\Plugins\Sirenix')) {
    $odinDlls = (Get-ChildItem (Join-Path $ProjectPath 'Assets\Plugins\Sirenix') -Recurse -Filter 'Sirenix.OdinInspector.Attributes.dll' -ErrorAction SilentlyContinue).Count
    if ($odinDlls -gt 0) { Ok 'Odin Inspector present (paid plugin, installed locally)' }
    else { Miss 'Sirenix dir exists but Odin assemblies missing (reinstall Odin Inspector 4.0.2.3)' }
}
else { Miss 'Odin Inspector missing: Assets/Plugins/Sirenix (per-seat paid, non-redistributable; install it yourself - see scripts/toolchain.json paidOrRestrictedPlugins)' }

if (Test-Path (Join-Path $ProjectPath 'Assets\Plugins\Demigiant\DOTween')) {
    Ok 'DOTween present (free plugin, installed locally)'
}
else { Miss 'DOTween missing: Assets/Plugins/Demigiant/DOTween (LiteGame.UI references DOTween.Modules; install free version from Asset Store)' }

if (Test-Path (Join-Path $ProjectPath 'Assets\Plugins\UniTask')) { Ok 'UniTask present' }
else { Miss 'UniTask missing: Assets/Plugins/UniTask (runtime required; should ship with repo)' }

if (Test-Path (Join-Path $ProjectPath 'Assets\Plugins\xlua.bundle')) { Ok 'xLua native plugin present' }
else { Miss 'xlua.bundle missing: Assets/Plugins/xlua.bundle (runtime required; should ship with repo)' }

# -- 5. Content items (WARN: not blocking for development) --------------------
if (Test-Path (Join-Path $ProjectPath 'Assets\LiteGame\Fonts')) { Ok 'Fonts dir present' }
else { Warn 'Assets/LiteGame/Fonts missing - CJK TMP text will render tofu (content not in repo; see restore guide)' }

if ((Test-Path (Join-Path $ProjectPath 'Assets\Scenes\Boot.unity')) -or (Test-Path (Join-Path $ProjectPath 'Assets\Scenes\Test.unity'))) {
    Ok 'At least one scene present (Test.unity is tracked)'
} else { Warn 'Assets/Scenes missing - cannot run directly' }

if (-not (Get-Command 'java' -ErrorAction SilentlyContinue)) {
    Warn 'JDK not detected - Android IL2CPP build (C0-2 mobile) needs JDK 11 + Android SDK/NDK (not blocking Windows dev)'
}

# -- Summary --------------------------------------------------------------------
Write-Host ''
if ($script:ok.Count -gt 0)      { foreach ($t in $script:ok)      { Write-Host "  [OK]   $t" -ForegroundColor Green } }
if ($script:warnings.Count -gt 0) { foreach ($t in $script:warnings) { Write-Host "  [WARN] $t" -ForegroundColor Yellow } }
if ($script:blocking.Count -gt 0) {
    Write-Host ''
    foreach ($t in $script:blocking) { Write-Host "  [MISS] $t" -ForegroundColor Red }
    Write-Host ''
    Write-Host "Restore check FAILED: $($script:blocking.Count) blocking item(s) - fix the list above and re-run" -ForegroundColor Red
    exit 1
}
Write-Host ''
Write-Host 'Restore check PASSED: workspace can open / run L1,L3 / proceed to build' -ForegroundColor Green
exit 0
