# -*- coding: utf-8 -*-
# M10 前置：联机版本 hash 生成器（2026-09-17）。
# 用途：Join 握手 buildHash 校验 + 启动期断言——两端 hash 不等 → 拒绝进房（《状态同步实施方案》§40/§380）。
#
# 覆盖范围（**两端必须逐字节一致的东西**）：
#   Assets/LiteSim/Core/Scripts/**   —— 判定逻辑（Sim 内所有确定性行为）
#   Assets/LiteNet/Proto/**          —— 协议单源（.proto + 生成物）
#   Assets/LiteNet/Protocol/**       —— 打包解包纯函数
#   **表数据**（DATA_TARGETS）        —— 玩法数值等：两端同读 GameData/Config 下的同一份二进制；
#                                       数值不同 = 行为分叉 → 必须同 hash（§3.3 buildHash 闭包）
#   注：Systems/ 与 Scripts/ 平级（2026-09-19 目录收纳的最终形态），同属判定源集，
#       漏了会让两端 System 分叉不被握手校验出来，故必须显式列入 TARGETS。
# 不覆盖：表现层/业务/UI（客户端差异不影响判定与协议）。
#
# 算法：按**相对路径（Ordinal）排序**后，逐个喂入 "相对路径\0<内容（行尾归一化）>" 到 SHA-256，
#       取前 16 个十六进制字符作 hash 值。确定性要点：
#   ① 排序固定（不依赖文件系统枚举顺序）
#   ② **行尾归一化**（CRLF/CR → LF）——否则不同机器 clone（git autocrlf）会算出不同 hash
#   ③ 排除自身输出（BuildHash.g.cs）与 bin/obj/.dotnet/.meta
#
# 重跑：改了 Sim 或协议后 → python scripts/gen-build-hash.py
# 守卫：**源集清单是单源**——本脚本同时生成 `Assets/LiteNet/Protocol/BuildHashSourceSet.g.cs`，
#       `Tests/LiteNet.Tests/BuildHashTests` 读它复算（跨语言不再各写一份，见
#       《客户端与服务端共享代码范围专项设计》§8.1 G1）。
import hashlib
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TARGETS = [
    'Assets/LiteSim/Core/Scripts',
    'Assets/LiteSim/Core/Systems',
    'Assets/LiteNet/Proto',
    'Assets/LiteNet/Protocol',
    # 安全信封（2026-10-03）：装饰在 Transport 上的线上协议层——密文帧形状/握手版本
    # 变更即两端 wire 不兼容，必须进 buildHash 闭包（KCP 适配层本体仍不入闭包：纯传输）。
    'Assets/LiteNet/Transport/Security',
]
DATA_TARGETS = [
    # 表数据两端同源（2026-09-28 起：服务端也读 .bytes——RoomServer 源链接 Generated + Luban 运行时，
    # 与客户端共编同一份代码、同读 GameData/Config 下同一份二进制）。
    # 2026-09-26：客户端 bin 从 Assets/LiteGame/RawFile/Config 移到 Assets/GameData/Config
    # ——与代码侧产物 Generated/ 同域（Luban 三份产物归拢），LiteGame 回归纯代码层。
    'Assets/GameData/Config',
]
DATA_EXTS = ('.bytes',)     # .meta 由 endswith('.meta') 排除（不会命中此白名单，双保险）

# 非玩法表排除（2026-09-25）：hash 只覆盖**会影响判定或协议的表**。UI 表（tbuiform）改一行界面配置
# 与对局行为无关，喂进 hash 会让"hash 变了但两端行为没变"——同 SKIP_DIRS 那条注释记录的坑：
# 旧例给菜单加一行注释导致全员拒绝进房，这里是同一病症的另一个入口（加一个反馈面 form 行）。
# 新增排除必须落在同一判据上：该表是否参与判定/协议。UI 布局、文本、图标属表现层。
DATA_EXCLUDE_NAMES = (
    'tbuiform.bytes',   # UI 表单：层级/路径/全屏——纯表现
)
OUT_FILE = os.path.join(ROOT, 'Assets', 'LiteNet', 'Protocol', 'BuildHash.g.cs')
SOURCE_SET_FILE = os.path.join(ROOT, 'Assets', 'LiteNet', 'Protocol', 'BuildHashSourceSet.g.cs')
# 生成器自身输出，收集时排除（否则自指不稳）。两个 .g.cs 都落在 LiteNet/Protocol（= hash 源集目录）
# 里，而收集规则是 `*.cs` 全收——不排除就会"污染自己"，且是**不收敛**的：
# 文件内容含 hash → hash 变 → 文件内容变 → hash 再变……（与源集无关的文件不该影响 hash）。
SELF_NAMES = ('BuildHash.g.cs', 'BuildHashSourceSet.g.cs')
SKIP_DIRS = {'bin', 'obj', '.dotnet', '__pycache__', 'Editor'}
# Editor 目录排除（2026-09-18 批③ 修正）：LiteSim.Core.csproj 的 Compile 通配带 Exclude="Scripts/Editor/**"
# ——编辑器脚本不在客户端/服务器共同编译的源集里，喂进 hash 会让"hash 变了但两端行为没变"
# （例如给菜单加一行注释 → 所有客户端与服务器握手上全部拒绝进房）。hash 只覆盖**共同源集**。


def collect():
    files = []
    for target in TARGETS:
        base = os.path.join(ROOT, target)
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for name in filenames:
                if not name.endswith('.cs'):
                    continue
                if name in SELF_NAMES or name.endswith('.meta'):
                    continue
                full = os.path.join(dirpath, name)
                rel = os.path.relpath(full, ROOT).replace('\\', '/')
                files.append((rel, full))
    for target in DATA_TARGETS:
        base = os.path.join(ROOT, target)
        if not os.path.isdir(base):
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for name in filenames:
                if not name.endswith(DATA_EXTS) or name.endswith('.meta'):
                    continue
                if name in DATA_EXCLUDE_NAMES:      # 非玩法表（见 DATA_EXCLUDE_NAMES 判据）
                    continue
                full = os.path.join(dirpath, name)
                rel = os.path.relpath(full, ROOT).replace('\\', '/')
                files.append((rel, full))
    files.sort(key=lambda x: x[0])          # Ordinal 排序（python 默认码点序，与 C# Ordinal 一致）
    return files


def normalize(raw):
    """行尾归一化：CRLF/CR → LF（跨机器 clone 一致性）。"""
    return raw.replace(b'\r\n', b'\n').replace(b'\r', b'\n')


def compute(files):
    h = hashlib.sha256()
    for rel, full in files:
        h.update(rel.encode('utf-8'))
        h.update(b'\x00')
        with open(full, 'rb') as f:
            h.update(normalize(f.read()))
    return h.hexdigest()[:16]


TEMPLATE = '''// <auto-generated: scripts/gen-build-hash.py —— DO NOT EDIT。源：LiteSim.Core/Scripts + LiteSim.Core/Systems
// + LiteNet/Proto + LiteNet/Protocol 的源码内容 + 表数据（GameData/Config）；改了 Sim/协议/表后重跑生成器。>
namespace LiteNet
{
    /// <summary>
    /// 联机版本 hash（M10 前置）：覆盖判定逻辑（Sim）与协议（Proto/Protocol）的源码内容，
    /// **两端（客户端/服务器）必须一致**——不一致 = 逻辑或协议版本不同 = 必然分叉。
    /// 用途：`JoinRequest.build_hash` 握手校验 + 启动期断言（不等 → 拒绝进房，§40/§380）；
    /// 生成规则见 `scripts/gen-build-hash.py`（含行尾归一化，保证跨机器可复现）；
    /// `Tests/LiteNet.Tests/BuildHashTests` 读 <see cref="BuildHashSourceSet"/> 按同规则复算并比对
    /// （防止改了源码忘重跑）。源集清单是**单源**——本文件只出常量，清单位于 BuildHashSourceSet.g.cs。
    /// </summary>
    public static class BuildHash
    {
        /// <summary>当前构建的版本 hash（16 位小写 hex）。</summary>
        public const string Value = "%s";
    }
}
'''

# 源集清单模板（G1 单源）：**同一脚本同时生成**，C# 守卫测试读这份而不是复写一份。
# 为什么必须单源：清单此前在 python 与 C# 各写一份，已经漂移过一次（C# 侧残留 RoomServer/Data + .json，
# 该目录 2026-09-28 已删 → 守卫对源集的复算有一半走空，且**不报错**）。
SOURCE_SET_TEMPLATE = '''// <auto-generated: scripts/gen-build-hash.py —— DO NOT EDIT。
// 源集清单**单源**：与 `scripts/gen-build-hash.py` 的 TARGETS / DATA_TARGETS / DATA_EXTS /
// DATA_EXCLUDE_NAMES / SKIP_DIRS 逐字对应，由同一脚本一并生成。
// `Tests/LiteNet.Tests/BuildHashTests` 读本文件复算——**跨语言不再各写一份**（见
// 《客户端与服务端共享代码范围专项设计》§8.1 G1：此前两处清单已漂移，守卫半失效且不报错）。>
namespace LiteNet
{
    /// <summary>BuildHash 源集清单（生成物，勿手改）。</summary>
    public static class BuildHashSourceSet
    {
        /// <summary>源码目标（相对仓库根，仅收集 *.cs）。</summary>
        public static readonly string[] Targets =
        {
%s        };

        /// <summary>表数据目标（相对仓库根，按 <see cref="DataExtensions"/> 白名单收集）。</summary>
        public static readonly string[] DataTargets =
        {
%s        };

        /// <summary>表数据扩展名白名单。</summary>
        public static readonly string[] DataExtensions =
        {
%s        };

        /// <summary>非玩法表排除（参与判定/协议以外的表不进 hash）。</summary>
        public static readonly string[] DataExcludeNames =
        {
%s        };

        /// <summary>收集时跳过的目录名。</summary>
        public static readonly string[] SkipDirs =
        {
%s        };

        /// <summary>生成器自身输出，收集时排除（否则自指不稳/不收敛）。</summary>
        public static readonly string[] SelfNames =
        {
%s        };
    }
}
'''


def _cs_array(items, indent='            '):
    return ''.join('%s"%s",\n' % (indent, item) for item in items)


def source_set_cs():
    """渲染源集清单 .g.cs（单源：与 collect() 实际使用的常量逐字一致）。"""
    return SOURCE_SET_TEMPLATE % (
        _cs_array(TARGETS),
        _cs_array(DATA_TARGETS),
        _cs_array(DATA_EXTS),
        _cs_array(DATA_EXCLUDE_NAMES),
        _cs_array(sorted(SKIP_DIRS)),
        _cs_array(SELF_NAMES),
    )


def main():
    files = collect()
    value = compute(files)
    with open(OUT_FILE, 'w', encoding='utf-8', newline='\n') as f:
        f.write(TEMPLATE % value)
    with open(SOURCE_SET_FILE, 'w', encoding='utf-8', newline='\n') as f:
        f.write(source_set_cs())
    print('BuildHash.g.cs written: %s (%d files)' % (value, len(files)))
    print('BuildHashSourceSet.g.cs written: %s' % SOURCE_SET_FILE)


if __name__ == '__main__':
    main()
